PARKING_STATUS_ENTER = -1
PARKING_STATUS_STOP = 0
PARKING_STATUS_LEAVE = 1
PARKING_STATUS_ANOMALY = 2

ALARM_TYPE_NONE = 0
ALARM_TYPE_WHISTLE = 1


LIFTER_STATUS_ANOMALY = -1
LIFTER_STATUS_AUTO = 0
LIFTER_STATUS_HAND = 1

DETECT_TYPE_CONFLICT = 1;

module.exports = {
    PARKING_STATUS_ENTER,
    PARKING_STATUS_STOP,
    PARKING_STATUS_LEAVE,
    PARKING_STATUS_ANOMALY,
    ALARM_TYPE_NONE,
    ALARM_TYPE_WHISTLE,
    LIFTER_STATUS_ANOMALY,
    LIFTER_STATUS_AUTO,
    LIFTER_STATUS_HAND,
    DETECT_TYPE_CONFLICT
}